services:
  web:
    build:
      context: .
    container_name: voting-app
    command: gunicorn voting_project.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
      - /app/staticfiles
    restart: always
