# Generated by Django 4.0.4 on 2022-04-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('user_code', models.CharField(max_length=15)),
                ('user_vote_count', models.IntegerField(default=0)),
            ],
        ),
    ]
