# Generated by Django 4.0.4 on 2022-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0003_alter_uservote_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_one', models.CharField(max_length=100)),
                ('unit_two', models.CharField(max_length=100)),
                ('unit_three', models.CharField(max_length=100)),
            ],
        ),
    ]
