# Generated by Django 4.0.4 on 2022-05-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0005_teachers_unit_one_glh_teachers_unit_three_glh_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Higher',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
