# Generated by Django 4.0.4 on 2022-05-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0006_rename_teachers_higher_delete_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Higher',
            new_name='Teachers',
        ),
    ]
