# Generated by Django 4.0.4 on 2022-06-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0011_higher_unit_five_higher_unit_five_glh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higher',
            name='unit_three',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='lower',
            name='unit_three',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
