# Generated by Django 4.0.4 on 2022-06-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0012_alter_higher_unit_three_alter_lower_unit_three'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higher',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='higher',
            name='unit_five',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='higher',
            name='unit_four',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='higher',
            name='unit_one',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='higher',
            name='unit_three',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='higher',
            name='unit_two',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lower',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lower',
            name='unit_five',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='lower',
            name='unit_four',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='lower',
            name='unit_one',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lower',
            name='unit_three',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='lower',
            name='unit_two',
            field=models.CharField(max_length=50),
        ),
    ]
